apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cassandra-jmx
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - cassandra-lab
  selector:
    matchLabels:
      app: cassandra
  podMetricsEndpoints:
    - port: jmx-metrics
      path: /metrics
      interval: 15s
