apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-jmx-exporter-config
  namespace: cassandra-lab
data:
  config.yaml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(used|max|committed|init):'
        name: jvm_memory_heap_$1_bytes
        type: GAUGE
      - pattern: 'java.lang<type=GarbageCollector,name=(.+)><>CollectionCount'
        name: jvm_gc_collection_count
        labels:
          collector: "$1"
        type: COUNTER
      - pattern: 'org.apache.cassandra.metrics<type=(\w+), name=(\w+)(?:, keyspace=(\w+))?(?:, scope=(\w+))?><>Count'
        name: cassandra_metrics_count
        labels:
          type: "$1"
          metric: "$2"
          keyspace: "$3"
          scope: "$4"
        type: COUNTER
      - pattern: '.*'
