grafana:
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring

prometheus:
  service:
    type: NodePort
    nodePort: 32090
  prometheusSpec:
    scrapeInterval: 1s
    evaluationInterval: 1s
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
