apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cassandra-simulator
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - cassandra-lab
  selector:
    matchLabels:
      app: cassandra-simulator
  podMetricsEndpoints:
    - port: http
      path: /metrics/prometheus
      interval: 15s
