apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-injector
  namespace: cassandra-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-injector
  namespace: cassandra-lab
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-injector
  namespace: cassandra-lab
subjects:
  - kind: ServiceAccount
    name: chaos-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-injector
